[settings]
# TODO: experimental
# python.uv_venv_auto = true

[env]
_.python.venv = { path = ".venv" }

[tasks.check]
description = "Validate cookie from .session"
run = "uv run aocli --check"

[tasks.solve]
description = "Run solutions for a given year or day."
run = "uv run aocli"

[tasks.watch]
description = "Watch for changes to solution files and re-run them."
run = "uv run aocli --watch"
